name: deploy

on:
  workflow_dispatch:

jobs:
  swarm-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Docker swarm
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: ${{ secrets.DEPLOY_HOST }}
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          deploy_path: /home/deploy/jarry-bot
          stack_file_name: docker-stack.yaml
          keep_files: 5
          args: jarry-bot